stages:
  - test

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

.e2e_template:
  image: mcr.microsoft.com/playwright:v1.41.2-jammy
  before_script:
    - npm ci --cache .npm --prefer-offline
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - playwright-report/
      - test-results/
      - junit.xml
    reports:
      junit: junit.xml

e2e_smoke_mr:
  extends: .e2e_template
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"
  script:
    - npx playwright test --grep @smoke
  timeout: 20m

e2e_regression_nightly:
  extends: .e2e_template
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - npx playwright test
  timeout: 60m